---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample
  name: sample
spec:
  ports:
  - nodePort: 32226
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sample
  type: NodePort
